name = "enhanced-multi-agent-workflow"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Durable Objects
[[durable_objects.bindings]]
name = "AGENT_COORDINATOR"
class_name = "AgentCoordinator"

[[durable_objects.bindings]]
name = "STATE_MANAGER"
class_name = "StateManager"

[[durable_objects.bindings]]
name = "INTEGRATION_DASHBOARD_AGENT"
class_name = "IntegrationDashboardAgent"

[[durable_objects.bindings]]
name = "REVIEW_MANAGER_AGENT"
class_name = "ReviewManagerAgent"

[[durable_objects.bindings]]
name = "CONTEXT_OPTIMIZER_AGENT"
class_name = "ContextOptimizerAgent"

[[durable_objects.bindings]]
name = "PATTERN_BRIDGE_AGENT"
class_name = "PatternBridgeAgent"

[[durable_objects.bindings]]
name = "LINEAR_STATE_AGENT"
class_name = "LinearStateAgent"

# KV Storage
[[kv_namespaces]]
binding = "CONFIG_KV"
id = "config_kv_namespace"
preview_id = "config_kv_preview"

# R2 Storage
[[r2_buckets]]
binding = "LOGS_BUCKET"
bucket_name = "workflow-logs"
preview_bucket_name = "workflow-logs-preview"

# Analytics Engine
[[analytics_engine_datasets]]
binding = "METRICS"
dataset = "workflow_metrics"

# Environment Variables
[vars]
ENVIRONMENT = "development"

# Secrets (set via wrangler secret put)
# LINEAR_API_KEY = "..."
# GITHUB_TOKEN = "..."
# SLACK_TOKEN = "..."
