apiVersion: v1
kind: Namespace
metadata:
  name: nba-betting
  labels:
    name: nba-betting
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nba-betting-quota
  namespace: nba-betting
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nba-betting-limits
  namespace: nba-betting
spec:
  limits:
  - default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container

